### ISSUE TITLE
ClassDecimalCollection:doubleSize

### ISSUE THREAD

**Issue by AlbertoNitro** [AlbertoNitro/IWVG.SwC.Alberto#3]
Crear nuevo metodo **doubleSize**

[+info sobre metodo](../wiki#doublesize)
[pautas](../wiki/Pautas-para-programadores)

**Comment by jchantej** [comment]
Se agrega un método para obtener un el resultado del tamaño de la lista multiplicada por dos.

**Comment by AlbertoNitro** [comment]
OK. No obstante, en el mensaje del commit deberias haber indicado "**ClassDecimalCollection:doubleSize**"
