### ISSUE TITLE
ClassFraction:addOneNumerator

### ISSUE THREAD

**Issue by AlbertoNitro** [AlbertoNitro/IWVG.SwC.Alberto#4]
Implementar nuevo metodo **addOneNumerator**

[+info sobre metodo](../wiki#addonenumerator)
[pautas](../wiki/Pautas-para-programadores)

**Comment by rploaiza** [comment]
Método creado addOneNumerator y realizadas las pruebas correspondientes en la clase Fraction.

**Comment by AlbertoNitro** [comment]
OK. Todo correcto.
