### ISSUE TITLE
ClassFraction:addTwoNumerator

### ISSUE THREAD

**Issue by AlbertoNitro** [AlbertoNitro/IWVG.SwC.Alberto#5]
Implementar nuevo metodo **addTwoNumerator**

[+info sobre metodo](../wiki#addtwonumerator)
[pautas](../wiki/Pautas-para-programadores)

**Comment by jchantej** [comment]
Se agrega metodo que permite sumar 2 al numerador de la fraccion.

**Comment by AlbertoNitro** [comment]
OK. No obstante, en el mensaje del commit deberias haber indicado "**ClassFraction:addTwoNumerator**"
